//! Manual Release experiments; fixtures are generated by scripts/make_perf_fixtures.py.
use crate::{budget::ByteBudget, decoding, models::ImageRecord, performance};
use std::{
    path::{Path, PathBuf},
    time::{Instant, UNIX_EPOCH},
};

fn record(path: &Path) -> ImageRecord {
    let meta = std::fs::metadata(path).unwrap();
    ImageRecord {
        id: 1,
        path: path.into(),
        relative_path: path.to_string_lossy().into_owned(),
        file_name: path.file_name().unwrap().to_string_lossy().into_owned(),
        size: meta.len(),
        modified_ns: meta
            .modified()
            .unwrap()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
            .min(i64::MAX as u128) as i64,
        width: None,
        height: None,
        format: path.extension().unwrap().to_string_lossy().into_owned(),
        thumbnail_key: "1".repeat(64),
        content_hash: None,
    }
}
#[test]
#[ignore = "requires TUHAI_FIXTURES, run in Release"]
fn jpeg_scaled_comparison_and_special_formats() {
    let root =
        PathBuf::from(std::env::var_os("TUHAI_FIXTURES").expect("TUHAI_FIXTURES")).join("special");
    let budget = ByteBudget::new(performance::DECODE_BYTES, performance::PREVIEW_RESERVE);
    for name in ["baseline-6000x4000.jpg", "baseline-8000x6000.jpg"] {
        let r = record(&root.join(name));
        for run in 0..5 {
            // Alternate order to reduce systematic filesystem-cache bias.
            for fast in if run % 2 == 0 {
                [false, true]
            } else {
                [true, false]
            } {
                let started = Instant::now();
                let size = if fast {
                    let output = decoding::decode(&r, 256, false, &budget, || false).unwrap();
                    (output.image.width, output.image.height)
                } else {
                    let output = image::open(&r.path)
                        .unwrap()
                        .resize(256, 256, image::imageops::FilterType::Triangle)
                        .into_rgba8();
                    (output.width() as usize, output.height() as usize)
                };
                assert!(size.0 <= 256 && size.1 <= 256);
                eprintln!(
                    "PERF {}",
                    serde_json::json!({"file":name,"run":run,"fast":fast,"ms":started.elapsed().as_secs_f64()*1000.0})
                );
                assert_eq!(budget.used(), 0);
            }
        }
    }
    for entry in std::fs::read_dir(&root).unwrap() {
        let path = entry.unwrap().path();
        let r = record(&path);
        let result = decoding::decode(&r, 256, false, &budget, || false);
        if path.file_name().unwrap() == "corrupt.jpg" {
            assert!(result.is_err());
        } else {
            assert!(result.is_ok(), "{}: {:?}", path.display(), result.err());
        }
    }
    let reference = decoding::decode(
        &record(&root.join("exif-1.jpg")),
        1024,
        true,
        &budget,
        || false,
    )
    .unwrap()
    .image;
    for orientation in 1..=8 {
        let result = decoding::decode(
            &record(&root.join(format!("exif-{orientation}.jpg"))),
            1024,
            true,
            &budget,
            || false,
        )
        .unwrap()
        .image;
        let mut expected = image::DynamicImage::ImageRgba8(
            image::RgbaImage::from_raw(
                reference.width as u32,
                reference.height as u32,
                reference.pixels.clone(),
            )
            .unwrap(),
        );
        expected.apply_orientation(image::metadata::Orientation::from_exif(orientation).unwrap());
        assert_eq!(
            result.pixels,
            expected.into_rgba8().into_raw(),
            "EXIF {orientation}"
        );
    }
}

#[test]
#[ignore = "requires TUHAI_REAL_FIXTURES; local samples only"]
fn real_jpeg_cache_compression() {
    use std::io::BufRead;
    let root = PathBuf::from(std::env::var_os("TUHAI_REAL_FIXTURES").expect("TUHAI_REAL_FIXTURES"));
    let manifest =
        std::io::BufReader::new(std::fs::File::open(root.join("manifest.jsonl")).unwrap());
    let budget = ByteBudget::new(performance::DECODE_BYTES, performance::PREVIEW_RESERVE);
    let (mut count, mut raw, mut compressed) = (0u64, 0u64, 0u64);
    for line in manifest.lines() {
        let entry: serde_json::Value = serde_json::from_str(&line.unwrap()).unwrap();
        if entry["format"] != "JPEG" {
            continue;
        }
        let output = decoding::decode(
            &record(&root.join(entry["fixture"].as_str().unwrap())),
            256,
            false,
            &budget,
            || false,
        )
        .unwrap();
        let encoded = crate::thumbnail_cache::encode(&output.image, true).unwrap();
        raw += output.image.pixels.len() as u64;
        compressed += encoded.len() as u64;
        count += 1;
        if count == 1000 {
            break;
        }
    }
    assert_eq!(count, 1000);
    eprintln!(
        "REAL_CACHE {}",
        serde_json::json!({"count": count, "rgba_bytes": raw, "container_bytes": compressed, "reduction": 1.0-compressed as f64/raw as f64})
    );
    assert!(compressed * 5 <= raw);
}

#[test]
#[ignore = "single-task native process peak; set TUHAI_PEAK_FAST and TUHAI_FIXTURES"]
fn single_jpeg_process_peak() {
    use windows::Win32::System::{
        ProcessStatus::{
            GetProcessMemoryInfo, PROCESS_MEMORY_COUNTERS, PROCESS_MEMORY_COUNTERS_EX,
        },
        Threading::GetCurrentProcess,
    };
    fn memory() -> (usize, usize) {
        let mut c = PROCESS_MEMORY_COUNTERS_EX::default();
        c.cb = std::mem::size_of_val(&c) as u32;
        unsafe {
            GetProcessMemoryInfo(
                GetCurrentProcess(),
                (&mut c as *mut PROCESS_MEMORY_COUNTERS_EX).cast::<PROCESS_MEMORY_COUNTERS>(),
                c.cb,
            )
            .unwrap();
        }
        (c.PrivateUsage, c.PeakWorkingSetSize)
    }
    let path = PathBuf::from(std::env::var_os("TUHAI_FIXTURES").unwrap())
        .join("special/baseline-8000x6000.jpg");
    let fast = std::env::var("TUHAI_PEAK_FAST").as_deref() == Ok("1");
    let before = memory();
    let budget = ByteBudget::new(performance::DECODE_BYTES, performance::PREVIEW_RESERVE);
    if fast {
        std::hint::black_box(
            decoding::decode(&record(&path), 256, false, &budget, || false).unwrap(),
        );
    } else {
        std::hint::black_box(
            image::open(path)
                .unwrap()
                .resize(256, 256, image::imageops::FilterType::Triangle)
                .into_rgba8(),
        );
    }
    let after = memory();
    eprintln!(
        "NATIVE_PEAK {}",
        serde_json::json!({"fast":fast,"initial_private":before.0,"peak_working_set":after.1,"initial_peak_working_set":before.1,"final_private":after.0})
    );
}
