//! Manual Release experiments; fixtures are generated by scripts/make_perf_fixtures.py.
use crate::{budget::ByteBudget, decoding, models::ImageRecord, performance};
use std::{
    path::{Path, PathBuf},
    time::{Instant, UNIX_EPOCH},
};

fn record(path: &Path) -> ImageRecord {
    let meta = std::fs::metadata(path).unwrap();
    ImageRecord {
        id: 1,
        path: path.into(),
        relative_path: path.to_string_lossy().into_owned(),
        file_name: path.file_name().unwrap().to_string_lossy().into_owned(),
        size: meta.len(),
        modified_ns: meta
            .modified()
            .unwrap()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
            .min(i64::MAX as u128) as i64,
        width: None,
        height: None,
        format: path.extension().unwrap().to_string_lossy().into_owned(),
        thumbnail_key: "1".repeat(64),
        content_hash: None,
    }
}
#[test]
#[ignore = "requires TUHAI_FIXTURES, run in Release"]
fn jpeg_scaled_comparison_and_special_formats() {
    let root =
        PathBuf::from(std::env::var_os("TUHAI_FIXTURES").expect("TUHAI_FIXTURES")).join("special");
    let budget = ByteBudget::new(performance::DECODE_BYTES, performance::PREVIEW_RESERVE);
    for name in ["baseline-6000x4000.jpg", "baseline-8000x6000.jpg"] {
        let r = record(&root.join(name));
        for run in 0..5 {
            // Alternate order to reduce systematic filesystem-cache bias.
            for fast in if run % 2 == 0 {
                [false, true]
            } else {
                [true, false]
            } {
                let started = Instant::now();
                let size = if fast {
                    let output = decoding::decode(&r, 256, false, &budget, || false).unwrap();
                    (output.image.width, output.image.height)
                } else {
                    let output = image::open(&r.path)
                        .unwrap()
                        .resize(256, 256, image::imageops::FilterType::Triangle)
                        .into_rgba8();
                    (output.width() as usize, output.height() as usize)
                };
                assert!(size.0 <= 256 && size.1 <= 256);
                eprintln!(
                    "PERF {}",
                    serde_json::json!({"file":name,"run":run,"fast":fast,"ms":started.elapsed().as_secs_f64()*1000.0})
                );
                assert_eq!(budget.used(), 0);
            }
        }
    }
    for entry in std::fs::read_dir(&root).unwrap() {
        let path = entry.unwrap().path();
        let r = record(&path);
        let result = decoding::decode(&r, 256, false, &budget, || false);
        if path.file_name().unwrap() == "corrupt.jpg" {
            assert!(result.is_err());
        } else {
            assert!(result.is_ok(), "{}: {:?}", path.display(), result.err());
        }
    }
    let reference = decoding::decode(
        &record(&root.join("exif-1.jpg")),
        1024,
        true,
        &budget,
        || false,
    )
    .unwrap()
    .image;
    for orientation in 1..=8 {
        let result = decoding::decode(
            &record(&root.join(format!("exif-{orientation}.jpg"))),
            1024,
            true,
            &budget,
            || false,
        )
        .unwrap()
        .image;
        let mut expected = image::DynamicImage::ImageRgba8(
            image::RgbaImage::from_raw(
                reference.width as u32,
                reference.height as u32,
                reference.pixels.clone(),
            )
            .unwrap(),
        );
        expected.apply_orientation(image::metadata::Orientation::from_exif(orientation).unwrap());
        assert_eq!(
            result.pixels,
            expected.into_rgba8().into_raw(),
            "EXIF {orientation}"
        );
    }
}
